name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

#      - name: Run tests
#        run: pytest

      - name: Deploy to Production via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/DebtAPI
            git pull origin master
            source .venv/bin/activate
            pip install -r requirements.txt
            make mig
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart debt_project.service
            sudo systemctl enable debt_project.service
            sudo systemctl restart nginx
            sudo systemctl enable nginx